CREATE TABLE public.orgs_org (
    id integer NOT NULL,
    is_active boolean NOT NULL,
    created_on timestamp with time zone NOT NULL,
    modified_on timestamp with time zone NOT NULL,
    uuid uuid NOT NULL,
    name character varying(128) NOT NULL,
    plan character varying(16) NOT NULL,
    plan_start timestamp with time zone,
    plan_end timestamp with time zone,
    stripe_customer character varying(32),
    language character varying(64),
    timezone character varying(63) NOT NULL,
    date_format character varying(1) NOT NULL,
    config text,
    slug character varying(255),
    is_anon boolean NOT NULL,
    is_flagged boolean NOT NULL,
    is_suspended boolean NOT NULL,
    uses_topups boolean NOT NULL,
    is_multi_org boolean NOT NULL,
    is_multi_user boolean NOT NULL,
    brand character varying(128) NOT NULL,
    surveyor_password character varying(128),
    country_id integer,
    created_by_id integer NOT NULL,
    modified_by_id integer NOT NULL,
    parent_id integer,
    limits jsonb NOT NULL,
    released_on timestamp with time zone,
    deleted_on timestamp with time zone,
    flow_languages character varying(3)[] NOT NULL
);